#!/bin/sh

if [ -e "$GIT_DIR/../bin/newver.sh" ]
then 
	$GIT_DIR/../bin/newver.sh -p
else 
	if [ -e "$GIT_DIR/../deps/teaser/bin/newver.sh" ] 
	then 
		$GIT_DIR/../deps/teaser/bin/newver.sh -p 
	else
		if [ -e "$GIT_DIR/../../teaser/bin/newver.sh" ] 
		then
			$GIT_DIR/../../teaser/bin/newver.sh -p
		fi
	fi 
fi
